
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizador;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MENOS = 18;
  public static final int MENOR = 25;
  public static final int ELSE = 27;
  public static final int PYC = 6;
  public static final int CADENA = 10;
  public static final int IGUAL = 20;
  public static final int INT = 3;
  public static final int EQUAL = 21;
  public static final int WHILE = 26;
  public static final int DECIMAL = 9;
  public static final int PARIZQ = 15;
  public static final int PARDER = 16;
  public static final int TRUE = 11;
  public static final int UMENOS = 19;
  public static final int IF = 13;
  public static final int ID = 5;
  public static final int LLAVEIZQ = 22;
  public static final int STRING = 2;
  public static final int LLAVEDER = 23;
  public static final int MAYOR = 29;
  public static final int EOF = 0;
  public static final int BREAK = 30;
  public static final int FALSE = 12;
  public static final int PRINT = 7;
  public static final int error = 1;
  public static final int BOOL = 14;
  public static final int ENTERO = 8;
  public static final int FOR = 24;
  public static final int MATCH = 28;
  public static final int MAS = 17;
  public static final int DOUBLE = 4;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "STRING",
  "INT",
  "DOUBLE",
  "ID",
  "PYC",
  "PRINT",
  "ENTERO",
  "DECIMAL",
  "CADENA",
  "TRUE",
  "FALSE",
  "IF",
  "BOOL",
  "PARIZQ",
  "PARDER",
  "MAS",
  "MENOS",
  "UMENOS",
  "IGUAL",
  "EQUAL",
  "LLAVEIZQ",
  "LLAVEDER",
  "FOR",
  "MENOR",
  "WHILE",
  "ELSE",
  "MATCH",
  "MAYOR",
  "BREAK"
  };
}

