
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analisis;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int PAR2 = 23;
  public static final int DOSPUNTOS = 9;
  public static final int PAR1 = 22;
  public static final int MULT = 18;
  public static final int CONST = 7;
  public static final int CHAR = 17;
  public static final int LLAVE2 = 41;
  public static final int EQUALS = 28;
  public static final int LLAVE1 = 40;
  public static final int IMPRIMIR = 13;
  public static final int ENTERO = 3;
  public static final int DIFERENTE = 29;
  public static final int DOUBLE = 15;
  public static final int INT = 14;
  public static final int FOR = 42;
  public static final int NOT = 33;
  public static final int FINCADENA = 12;
  public static final int MENORIGUAL = 31;
  public static final int AND = 34;
  public static final int IGUAL = 27;
  public static final int CARACTER = 5;
  public static final int OR = 35;
  public static final int BOOL = 39;
  public static final int DIV = 19;
  public static final int INCREMENTO = 10;
  public static final int IF = 38;
  public static final int UMENOS = 26;
  public static final int ID = 6;
  public static final int MAYORIGUAL = 32;
  public static final int EOF = 0;
  public static final int DECIMAL = 4;
  public static final int TRUE = 36;
  public static final int DECREMENTO = 11;
  public static final int error = 1;
  public static final int CADENA = 2;
  public static final int MODULO = 21;
  public static final int MENOS = 25;
  public static final int MENOR = 43;
  public static final int BREAK = 44;
  public static final int MAYOR = 30;
  public static final int POTENCIA = 20;
  public static final int STRING = 16;
  public static final int FALSE = 37;
  public static final int VAR = 8;
  public static final int MAS = 24;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "CADENA",
  "ENTERO",
  "DECIMAL",
  "CARACTER",
  "ID",
  "CONST",
  "VAR",
  "DOSPUNTOS",
  "INCREMENTO",
  "DECREMENTO",
  "FINCADENA",
  "IMPRIMIR",
  "INT",
  "DOUBLE",
  "STRING",
  "CHAR",
  "MULT",
  "DIV",
  "POTENCIA",
  "MODULO",
  "PAR1",
  "PAR2",
  "MAS",
  "MENOS",
  "UMENOS",
  "IGUAL",
  "EQUALS",
  "DIFERENTE",
  "MAYOR",
  "MENORIGUAL",
  "MAYORIGUAL",
  "NOT",
  "AND",
  "OR",
  "TRUE",
  "FALSE",
  "IF",
  "BOOL",
  "LLAVE1",
  "LLAVE2",
  "FOR",
  "MENOR",
  "BREAK"
  };
}

